stages:
    - build
    - test
    - deploy

build-job:
    stage: build
    script:
        - docker build -t dirclass:v1 .

test-job:
    stage: test
    script:
        - docker run --rm dirclass:v1 npm run test

deploy-job:
    stage: deploy
    script:
        - docker compose up -d
