services:
    dirclass:
        image: dirclass:v1
        container_name: dirclass
        restart: unless-stopped
        ports:
            - '127.0.0.1:3005:3005'
        environment:
            HOST: '0.0.0.0'
            PORT: 3005
        volumes:
            - dirclass_data:/data
volumes:
    dirclass_data:
