services:
    dirclass:
        image: dirclass:v1
        container_name: dirclass
        restart: unless-stopped
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.dirclass.rule=Host(`ionrusu114.pro`)'
            - 'traefik.http.services.dirclass.loadbalancer.server.port=3005'
        environment:
            HOST: '0.0.0.0'
            PORT: 3005

        volumes:
            - dirclass_data:/data
volumes:
    dirclass_data:

networks:
    default:
        name: proxynet
        external: true
